export const modes = {
  bot: {
    bot: true,
    scoreboard: true,
    countdown: 3,
    clock: true,
    training: false,
    infiniteBoost: false,
    goal: "celebrate",
  },
  heatseeker: {
    bot: true,
    scoreboard: true,
    countdown: 3,
    clock: true,
    training: false,
    infiniteBoost: false,
    goal: "celebrate",
  },
  freeplay: {
    bot: false,
    scoreboard: false,
    countdown: 0,
    clock: false,
    training: true,
    infiniteBoost: true,
    goal: "practice",
  },
  rings: {
    bot: false,
    scoreboard: false,
    countdown: 0,
    clock: false,
    training: false,
    infiniteBoost: true,
    goal: "practice",
  },
  "dribbling-race": {
    bot: true,
    scoreboard: false,
    countdown: 0,
    clock: false,
    training: false,
    infiniteBoost: true,
    goal: "practice",
  },
  "solo-dribbling": {
    bot: false,
    scoreboard: false,
    countdown: 0,
    clock: false,
    training: false,
    infiniteBoost: true,
    goal: "practice",
  },
  "bot-ranked": {
    bot: true,
    scoreboard: true,
    countdown: 3,
    clock: true,
    training: false,
    infiniteBoost: false,
    goal: "celebrate",
  },
  party: {
    bot: false,
    scoreboard: true,
    countdown: 3,
    clock: true,
    training: false,
    infiniteBoost: false,
    goal: "celebrate",
  },
} as const;
export type Mode = keyof typeof modes;
